version: '3'

services:
  php:
    container_name: php
    restart: "always"
    build:
      context: ./php
    volumes:
      - ./application:/var/www/symfony
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./application:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/502.html:/var/www/502.html
    depends_on:
      - php
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
